name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-js:
    name: Lint JavaScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        run: npm ci

      - name: Lint Prettier
        run: npm run lint:prettier
